"/odometrypublisher":
  "ros__parameters":
    "gt_topic_name": "/Alpha/gt_xyz"
    "number_of_skips": 1
    "pcl_topic_name": "/Alpha/velodyne_points"
    "pose_topic_name": "/Alpha/poseArray"
    "scan_radius_max": 15.0
    "time_until_save": 1
    "which_registration": "fs3d32"
